spring:
  application:
    name: ${APP_NAME}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  jackson:
    property-naming-strategy: SNAKE_CASE


springdoc:
  swagger-ui:
    operations-sorter: method
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs

application:
  security:
    jwt:
      secret-key:
        public: classpath:public-key.pem
        private: classpath:private-key.pem
      expiration: ${JWT_EXPIRATION:3600}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:86400}

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              basicBinder: TRACE