name: Push Workflow

on:
  push:
    branches:
      - main

concurrency:
  group: push-workflow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonar-analyze-backend:
    uses: ./.github/workflows/sonar-backend.yml
    secrets:
      PRIVATE_SECRET_PEM: ${{ secrets.PRIVATE_SECRET_PEM }}
      SONAR_TOKEN_BACKEND: ${{ secrets.SONAR_TOKEN_BACKEND }}

  sonar-analyze-frontend:
    uses: ./.github/workflows/sonar-frontend.yml
    secrets:
      SONAR_TOKEN_FRONTEND: ${{ secrets.SONAR_TOKEN_FRONTEND }}
